# paths=/api/testcases/run,/api/testcases/diff,/api/testcases/all,/api/testcases/prompt
paths=/run,/diff,/all,/prompt,/results,/results/pdf

services=AttendanceService,EmployeeService
repos=AttendanceRepo,EmployeeRepo
models=AttendanceModel,EmployeeModel
