spring.application.name=college
spring.datasource.url=jdbc:mysql://localhost:3306/attendance
spring.datasource.username=root
spring.datasource.password=Change123
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Show which controller mappings are registered
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE

# Show request handling & matching
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG

# Show why a request was rejected (404 reason)
logging.level.org.springframework.web.servlet.handler.AbstractHandlerMapping=TRACE
